config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'

  post 'recipes/index'
  

  root 'recipes#index'

end

app/models/recipe.rb
# class Recipe < ActiveRecord::Base
class Recipe
   include HTTParty

   hostport = ENV['FOOD2FORK_SERVER_AND_PORT'] || 'www.food2fork.com'
   user_key = ENV['FOOD2FORK_KEY']

   base_uri "http://#{hostport}/api"
   default_params key: user_key
   format :json

   def self.for term
      get("/search", query: {q: term})["recipes"]
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @search_term = params[:search] || ""
    @recipes = Recipe.for(@search_term)
  end

  def search
  	@search_term = params[:search]
     @recipes = Recipe.for(@search_term)
    redirect_to "recipes/index/?search=#{params[:search]}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Recipefinder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="headers">
		<div id="header-image">
			<%= image_tag("wreath-grey.jpg") %>
		</div>
		<div id="header-text">
	 	<h1> Recipe Hunter App </h1>
		</div>
	</div>
	 <%= form_tag recipes_index_path do %>
	  <p id="search">
	    <%= text_field_tag :search %>
	    <%= submit_tag "Search", :name => nil, :class => "button"%>
	  </p>
<% end %>

<%= yield %>

<p>Powered By Food2Fork.com</p>

</body>
</html>

app/views/recipes/index.html.erb
<h3 id="Query">Searching for - <%= @search_term %></h3>

<% if @recipes.nil? %>
    <p>No recipes found with relevant information.... !!! </p>
<% else %>
    <table border="1">
        <tr>
            <th id="Thumbnail">Thumbnail</th>
            <th id="Title">Title</th>
            <th id="SR">Social Rank</th>
        </tr>
        <% @recipes.each do |recipe| %>
        <tr>
            <td><%= link_to( image_tag(recipe["image_url"], height: '250', width: '250') , recipe['source_url']) %></td>
            <td style="text-align: center;"><%= link_to(sanitize(recipe["title"]), recipe['source_url']) %></td>
            <td style="text-align: center;"><%= recipe["social_rank"].round %></td>
        </tr>
        <% end %>
    </table>
<% end %>